### ISSUE TITLE
Pi-Hole nicht kompatibel mit JS-Controller 5

### ISSUE THREAD

**Issue by Voodoo2man** [unltdnetworx/ioBroker.pi-hole#45]
Der Pi-Hole Adapter startet nach dem Update auf JS-Controller 5.0.2 nicht mehr.

Die Ampel bleibt rot. (Verbunden mit Host und Lebenszeichen sind weiterhin rot)

uncaught exception: Parameter "options" needs to be a real object but type "object" has been passed

Error: Parameter "options" needs to be a real object but type "object" has been passed at Validator.assertObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/validator.js:215:19) at AdapterClass.setObjectNotExists (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:3388:35) at main (/opt/iobroker/node_modules/iobroker.pi-hole/main.js:327:10) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.pi-hole/main.js:75:6) at process.processImmediate (node:internal/timers:478:21)

Parameter "options" needs to be a real object but type "object" has been passed

Adapter Version: 1.3.4
JS-Controller 5.0.2
Node Version 18.16.0
RaspberryPi OS

**Comment by DschungelDaddy** [comment]
Ich kann dies, nach heutigem JS-Controller Update, bestätigen.

I can confirm this, after today's JS controller update.

**Comment by unltdnetworx** [comment]
Bitte mal über Github updaten. Sollte wieder laufen.

**Comment by luieiob** [comment]
Fehler ist noch vorhanden

host.iobroker
2023-06-14 20:28:59.251	warn	Do not restart adapter system.adapter.pi-hole.0 because restart loop detected
host.iobroker
2023-06-14 20:28:59.251	info	Restart adapter system.adapter.pi-hole.0 because enabled
host.iobroker
2023-06-14 20:28:59.251	error	instance system.adapter.pi-hole.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
pi-hole.0
2023-06-14 20:28:58.643	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
pi-hole.0
2023-06-14 20:28:58.642	info	terminating
pi-hole.0
2023-06-14 20:28:58.642	info	cleaned everything up...
pi-hole.0
2023-06-14 20:28:58.641	error	Parameter "options" needs to be a real object but type "object" has been passed
pi-hole.0
2023-06-14 20:28:58.640	error	Error: Parameter "options" needs to be a real object but type "object" has been passed at Validator.assertObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/validator.js:215:19) at AdapterClass.setObjectNotExists (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:3388:35) at main (/opt/iobroker/node_modules/iobroker.pi-hole/main.js:327:10) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.pi-hole/main.js:75:6) at process.processImmediate (node:internal/timers:478:21)
pi-hole.0
2023-06-14 20:28:58.639	error	uncaught exception: Parameter "options" needs to be a real object but type "object" has been passed
pi-hole.0
2023-06-14 20:28:58.614	info	starting. Version 1.3.4 (non-npm: unltdnetworx/ioBroker.pi-hole) in /opt/iobroker/node_modules/iobroker.pi-hole, node: v18.16.0, js-controller: 5.0.3``

**Comment by bimbolongo** [comment]
Das Update auf die Version 1.3.5 ist jetzt im Beta Repo von Iobroker. Leider funktioniert das Update nicht und die Version bleibt bei 1.3.4.

$ iobroker upgrade pi-hole@1.3.5 --debug
Update pi-hole from @1.3.4 to @1.3.5
NPM version: 9.5.1
Installing iobroker.pi-hole@1.3.5... (System call)
npm ERR! code ETARGETnpm ERR! notarget No matching version found for js-controller@>=2.0.0.npm ERR! notarget In most cases you or one of your dependencies are requestingnpm ERR! notarget a package version that doesn't exist.npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2023-06-15T23_10_19_110Z-debug-0.log
upload [4] pi-hole.admin /opt/iobroker/node_modules/iobroker.pi-hole/admin/admin.d.ts admin.d.ts video/mp2t
upload [3] pi-hole.admin /opt/iobroker/node_modules/iobroker.pi-hole/admin/index_m.html index_m.html text/html
upload [2] pi-hole.admin /opt/iobroker/node_modules/iobroker.pi-hole/admin/pi-hole.png pi-hole.png image/png
upload [1] pi-hole.admin /opt/iobroker/node_modules/iobroker.pi-hole/admin/style.css style.css text/css
upload [0] pi-hole.admin /opt/iobroker/node_modules/iobroker.pi-hole/admin/words.js words.js application/javascript
Process exited with code 0

**Comment by unltdnetworx** [comment]
Bitte nochmal über Github testen

**Comment by Rookiestyle** [comment]
1.3.6 über GitHub funktioniert bei mir

**Comment by luieiob** [comment]
kann ich bestätigen, 1.3.6 über Github funktioniert

**Comment by Voodoo2man** [comment]
Bei mir auch. Vielen Dank!

**Comment by bimbolongo** [comment]
Läuft. Danke Schön!

**Comment by unltdnetworx** [comment]
Danke fürs Bescheid geben
